BitBookApp/Models/ProfileImage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BitBookApp.Models
{
    public class ProfileImage
    {
        [Key]
        public int ProfileImageId { get; set; }

        public int UserId { get; set; }

        [Required(ErrorMessage = "Image type is required")]
        [Display(Name = "Image Type")]
        public int ImageTypeId { get; set; }

        [Required(ErrorMessage = "Image is required")]
        [Display(Name = "Profile Photo")]
        public byte[] UserImage { get; set; }
    }
}

BitBookApp/Controllers/ProfileImageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BitBookApp.Models;

namespace BitBookApp.Controllers
{
    public class ProfileImageController : Controller
    {
        private BitBookDbContext db = new BitBookDbContext();

        // GET: /ProfileImage/
        public ActionResult Index()
        {
            return View(db.ProfileImages.ToList());
        }

        // GET: /ProfileImage/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProfileImage profileimage = db.ProfileImages.Find(id);
            if (profileimage == null)
            {
                return HttpNotFound();
            }
            return View(profileimage);
        }

        // GET: /ProfileImage/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /ProfileImage/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProfileImage profileimage, HttpPostedFileBase image)
        {
            bool status;

                try
                {

                    byte[] bytes;
                    int BytestoRead;
                    int numBytesRead;
                    if (image != null)
                    {
                        bytes = new byte[image.ContentLength];
                        BytestoRead = (int)image.ContentLength;
                        numBytesRead = 0;
                        while (BytestoRead > 0)
                        {
                            int n = image.InputStream.Read(bytes, numBytesRead, BytestoRead);
                            if (n == 0) break;
                            numBytesRead += n;
                            BytestoRead -= n;
                        }
                        profileimage.UserImage = bytes;
                        profileimage.UserId = Convert.ToInt32(Session["UserId"]);

                        db.ProfileImages.Add(profileimage);
                        db.SaveChanges();

                        status = true;
                    }
                    else
                    {
                        status = false;
                    }
                }
                catch (Exception)
                {
                    status = false;
                }

            if (status)
            {
                return RedirectToAction("Index", "Profile");
            }
            return View(profileimage);
        }

        // GET: /ProfileImage/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProfileImage profileimage = db.ProfileImages.Find(id);
            if (profileimage == null)
            {
                return HttpNotFound();
            }
            return View(profileimage);
        }

        // POST: /ProfileImage/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ProfileImageId,UserId,ImageTypeId,Image")] ProfileImage profileimage)
        {
            if (ModelState.IsValid)
            {
                db.Entry(profileimage).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(profileimage);
        }

        // GET: /ProfileImage/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProfileImage profileimage = db.ProfileImages.Find(id);
            if (profileimage == null)
            {
                return HttpNotFound();
            }
            return View(profileimage);
        }

        // POST: /ProfileImage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProfileImage profileimage = db.ProfileImages.Find(id);
            db.ProfileImages.Remove(profileimage);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BitBookApp/Views/ProfileImage/Create.cshtml
@model BitBookApp.Models.ProfileImage

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutBb.cshtml";
}

@using (Html.BeginForm("Create", "ProfileImage", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Add Picture</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.ImageTypeId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.TextBoxFor(model => model.ImageTypeId, new { @class = "form-control"})*@
                @Html.DropDownListFor(model => model.ImageTypeId, new List<SelectListItem>
                {
                    new SelectListItem{ Text="Cover Picture", Value = "1" },
                    new SelectListItem{ Text="Profile Picture", Value = "2" }
                    }, "--Select--", new { @class = "form-control"})
                @Html.ValidationMessageFor(model => model.ImageTypeId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserImage, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="image" name="image" />
                @*@Html.EditorFor(model => model.Image)*@
                @Html.ValidationMessageFor(model => model.UserImage)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Profile")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BitBookApp/Views/ProfileImage/Delete.cshtml
@model BitBookApp.Models.ProfileImage

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProfileImage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageTypeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageTypeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BitBookApp/Views/ProfileImage/Details.cshtml
@model BitBookApp.Models.ProfileImage

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ProfileImage</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageTypeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageTypeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProfileImageId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BitBookApp/Views/ProfileImage/Edit.cshtml
@model BitBookApp.Models.ProfileImage

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProfileImage</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ProfileImageId)

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId)
                @Html.ValidationMessageFor(model => model.UserId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageTypeId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageTypeId)
                @Html.ValidationMessageFor(model => model.ImageTypeId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image)
                @Html.ValidationMessageFor(model => model.Image)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BitBookApp/Views/ProfileImage/Index.cshtml
@model IEnumerable<BitBookApp.Models.ProfileImage>
@*@model BitBookApp.Models.ProfileImage*@

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageTypeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserImage)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImageTypeId)
        </td>
        <td>
            <img src="data:image;base64,@System.Convert.ToBase64String(item.UserImage)" width="200" height="200" />
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ProfileImageId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ProfileImageId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ProfileImageId })
        </td>
    </tr>
}

</table>