BitBookApp/Controllers/LoginController.cs
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using BitBookApp.Models;

namespace BitBookApp.Controllers
{
    public class LoginController : Controller
    {
        private BitBookDbContext db = new BitBookDbContext();
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Login login)
        {
            if (ModelState.IsValid)
            {
                if (db.Registrations.FirstOrDefault(x => x.EmailAddress.Contains(login.EmailAddress) && x.Password.Contains(login.Password)) != null)
                {
                    FormsAuthentication.SetAuthCookie(login.EmailAddress, true);
                    Session["Username"] = login.EmailAddress;
                    Session["UserId"] = db.Registrations.Where(x => x.EmailAddress == login.EmailAddress).Select(x => x.UserId).FirstOrDefault();
                    
                    return RedirectToAction("Index", "Home");
                }
                ViewBag.Error = "Login Failed";
            }
            return View();
        }

        public ActionResult Logout()
        {
            if (Request.Cookies[FormsAuthentication.FormsCookieName] != null)
            {
                FormsAuthentication.SignOut();
                Session.Clear();
                Session.Abandon();
            }
            return Redirect("~/Login/Index");
        }
	}
}

BitBookApp/Controllers/ProfileController.cs
using System;
using System.Data;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BitBookApp.Models;

namespace BitBookApp.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private BitBookDbContext db = new BitBookDbContext();

        // GET: /Profile/
        public ActionResult Index()
        {
            int userId = Convert.ToInt32(Session["UserId"]);

            var coverPictures = db.ProfileImages.Where(x => x.UserId == userId && x.ImageTypeId == 1).ToList();
            ViewBag.CoverPicture = coverPictures;

            var profilePicture = db.ProfileImages.Where(x => x.UserId == userId && x.ImageTypeId == 2).ToList();
            ViewBag.ProfilePicture = profilePicture;

            var education = db.Educations.Where(x => x.UserId == userId).ToList();
            ViewBag.Education = education;

            var experience = db.Experiences.Where(x => x.UserId == userId).ToList();
            ViewBag.Experience = experience;

            return View(db.UserProfiles.FirstOrDefault(x => x.UserId == userId));
        }

        public ActionResult ProfileView(int? id)
        {
            var coverPictures = db.ProfileImages.Where(x => x.UserId == id && x.ImageTypeId == 1).ToList();
            ViewBag.CoverPicture = coverPictures;

            var profilePicture = db.ProfileImages.Where(x => x.UserId == id && x.ImageTypeId == 2).ToList();
            ViewBag.ProfilePicture = profilePicture;

            var education = db.Educations.Where(x => x.UserId == id).ToList();
            ViewBag.Education = education;

            var experience = db.Experiences.Where(x => x.UserId == id).ToList();
            ViewBag.Experience = experience;

            return View("Index", db.UserProfiles.FirstOrDefault(x => x.UserId == id));
        }

        // GET: /Profile/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        // GET: /Profile/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Profile/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ProfileId,UserId,Name,Gender,Contact,City,Country,AreaOfInterest,ProfilePhoto,CoverPhoto")] UserProfile userprofile)
        {
            userprofile.UserId = Convert.ToInt32(Session["UserId"]);

            if (ModelState.IsValid)
            {
                db.UserProfiles.Add(userprofile);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userprofile);
        }

        // GET: /Profile/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        // POST: /Profile/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ProfileId,UserId,Name,Gender,Contact,City,Country,AreaOfInterest,ProfilePhoto,CoverPhoto")] UserProfile userprofile)
        {
            userprofile.UserId = Convert.ToInt32(Session["UserId"]);
            if (ModelState.IsValid)
            {
                db.Entry(userprofile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userprofile);
        }

        // GET: /Profile/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        // POST: /Profile/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            db.UserProfiles.Remove(userprofile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult SearchFreind(string searchFriend)
        {
            var profilePicture = db.ProfileImages.Where(x => x.ImageTypeId == 2).ToList();
            ViewBag.ProfilePicture = profilePicture;

            var friends = db.UserProfiles.Where(x => x.Name.Contains(searchFriend)).ToList();

            return View(friends);
        }

        public ActionResult SendFriendRequest(int? id)
        {
            return View(db.UserProfiles.FirstOrDefault(x => x.UserId == id));
        }

        [HttpPost]
        public ActionResult SendFriendRequest(UserProfile userProfile)
        {
            Friend friend = new Friend();
            friend.UserId = Convert.ToInt32(Session["UserId"]);
            friend.FriendId = userProfile.UserId;

            if (ModelState.IsValid)
            {
                if (db.Friends.Count(x=> x.FriendId == friend.FriendId && x.UserId == friend.UserId) == 0)
                {
                    db.Friends.Add(friend);
                    db.SaveChanges();
                    return RedirectToAction("Index", "Home");
                }
                ViewBag.Exist = "Already sent friend request";
            }
            return View();
        }

        public ActionResult ViewFriendRequest()
        {
            int userId = Convert.ToInt32(Session["UserId"]);

            var profilePicture = db.ProfileImages.Where(x => x.ImageTypeId == 2).ToList();
            ViewBag.ProfilePicture = profilePicture;

            var friendList =
                db.Friends.Join(db.UserProfiles, up => up.UserId, f => f.UserId, (up, f) => new {up, f})
                    .Where(x => x.up.FriendId == userId && x.up.Status.Equals(false)).Select (m => new ViewFriendRequiest
                    {
                        FriendId = m.up.UserId,
                        FriendName = m.f.Name,
                    }).ToList();

            ViewBag.FriendList = friendList;

            return View(friendList);
        }

        public ActionResult ConfirmRequest(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userprofile = db.UserProfiles.FirstOrDefault(x=>x.UserId == id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        [HttpPost]
        public ActionResult ConfirmRequest(int id)
        {
            foreach (var friend in db.Friends.Where(x => x.UserId == id).ToList())
            {
                friend.Status = true;
            }
            db.SaveChanges();

            UserProfile userprofile = db.UserProfiles.FirstOrDefault(x => x.UserId == id);

            return View("Confirmation", userprofile);
        }

        public ActionResult ViewFriend()
        {
            int userId = Convert.ToInt32(Session["UserId"]);

            var profilePicture = db.ProfileImages.Where(x => x.ImageTypeId == 2).ToList();
            ViewBag.ProfilePicture = profilePicture;

            var friendList =
                db.Friends.Join(db.UserProfiles, up => up.UserId, f => f.UserId, (up, f) => new { up, f })
                    .Where(x => x.up.FriendId == userId && x.up.Status.Equals(true) || x.up.UserId == userId && x.up.Status.Equals(true)).Select(m => new ViewFriendRequiest
                    {
                        FriendId = m.up.UserId,
                        FriendName = m.f.Name,
                    }).ToList();

            ViewBag.FriendList = friendList;

            return View(friendList);
        }

        public ActionResult Unfriend(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userprofile = db.UserProfiles.FirstOrDefault(x => x.UserId == id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        [HttpPost]
        public ActionResult Unfriend(int id)
        {
            foreach (var friend in db.Friends.Where(x => x.UserId == id).ToList())
            {
                friend.Status = false;
            }
            db.SaveChanges();

            UserProfile userprofile = db.UserProfiles.FirstOrDefault(x => x.UserId == id);

            return View("UnfriendConfirmation", userprofile);
        }
    }
}

BitBookApp/Controllers/RegistrationController.cs
using System;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BitBookApp.Models;

namespace BitBookApp.Controllers
{
    public class RegistrationController : Controller
    {
        private BitBookDbContext db = new BitBookDbContext();

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,EmailAddress,Password,ConfirmPassword")] UserRegistration userregistration)
        {
            if (ModelState.IsValid)
            {
                if (db.Registrations.Where(x => x.EmailAddress == userregistration.EmailAddress).Select(x=>x.EmailAddress).FirstOrDefault() == null)
                {
                    db.Registrations.Add(userregistration);
                    db.SaveChanges();
                    return RedirectToAction("Index", "Login");
                }
                ViewBag.Error = "Email address already exists";
            }
            return View(userregistration);
        }

        public ActionResult Edit()
        {
            int id = Convert.ToInt32(Session["UserId"]);

            UserRegistration userRegistration = db.Registrations.FirstOrDefault(x=> x.UserId == id);
            if (userRegistration == null)
            {
                return HttpNotFound();
            }
            return View("ChangePassword", userRegistration);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserRegistration userRegistration)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userRegistration).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.Success = "Password updated successfully";
            }
            return View("ChangePassword");
        }
    }
}

BitBookApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="container-fluid">

        <div class="row">
            <div class="col-md-9">

            </div>

            <div class="col-md-3">
                @*@if (Session["UserId"] != null)
                {
                    <span>
                        Hello @Session["Username"].ToString()
                        @Html.ActionLink("Logout", "Logout", "Login", new { @Style = "color:White" }, null)
                    </span>
                }
                else
                {
                    @Html.ActionLink("Login", "Index", "Login")
                }*@
            </div>
        </div>

    </div>





    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BitBookApp/Views/Shared/_LayoutBb.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        .headertable table tr td {
            padding: 10px;
        }

        .headerlink a {
            font-weight: bold;color: white;
        }

        .headerlink a:hover {
            color: white;
            font-weight: bold;
            text-decoration: none;
        }
    </style>

</head>
<body>

    <div class="container-fluid headerlink headertable">

        <div class="row" style="background-color: #3F5C9A; color: white; height: 50px">
            <div class="col-md-12">
                <table style="width: 100%">
                    <tr>
                        <td style="width: 8%"></td>
                        <td>
                            <div class="searchBox">
                                @using (@Html.BeginForm("SearchFreind", "Profile"))
                                {

                                    <div class="container">
                                        <div class="row">
                                            <div class="col-sm-8">
                                                <div id="imaginary_container">
                                                    <div class="input-group stylish-input-group">
                                                        <input type="text" id="searchFriend" name="searchFriend" placeholder="Search friend...." class="form-control">
                                                        <span class="input-group-addon">
                                                            <button type="submit" value="Search" style="height: 20px;">
                                                                <span class="glyphicon glyphicon-search"></span>
                                                            </button>
                                                        </span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }

                            </div>
                        </td>
                        <td>
                            <div class="dropdown">
                                <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                                    Settings
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("View Friend", "ViewFriend", "Profile")</li>
                                    <li>@Html.ActionLink("Change Password", "Edit", "Registration")</li>
                                </ul>
                            </div>
                        </td>
                        <td>
                            @Html.ActionLink("Profile", "Index", "Profile") |
                            @Html.ActionLink("Home", "Index", "Home")
                        </td>
                        <td>
                            <label>
                                <a href="/Profile/ViewFriendRequest">
                                    <img id="friendRequest" class="friendRequest" src="~/Images/FriendRequest.jpg" style="width: 30px; height: 30px;" /> &nbsp;&nbsp;

                                </a>
                            </label>

                            <label style="color: #ff0000">
                                @if (@ViewBag.RequestCount != 0)
                                {@ViewBag.RequestCount
                                }
                            </label>

                            <label>
                                <a href="/Profile/Notification">
                                    <img id="notification" class="friendRequest" src="~/Images/NotificationLogo.jpg" style="width: 30px; height: 30px;" />
                                </a>
                            </label>

                            <label style="color: #ff0000">
                                @if (@ViewBag.NotificationCount != 0)
                                {
                                    @ViewBag.NotificationCount
                                }
                            </label>
                        </td>
                        <td>
                            @if (Session["UserId"] != null)
                            {
                                <span>
                                    Hello @Session["Username"].ToString()
                                    @Html.ActionLink("Logout", "Logout", "Login", new { @Style = "color:White" }, null)
                                </span>
                            }
                            else
                            {
                                @Html.ActionLink("Login", "Index", "Login")
                            }
                        </td>
                    </tr>
                </table>
            </div>
        </div>

    </div>





    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>